Refactoring code

diff --git a/bin/omarchy-update b/bin/omarchy-update
--- a/bin/omarchy-update
+++ b/bin/omarchy-update
@@ -2,10 +2,10 @@
 
 set -e
 
-trap 'echo ""; echo -e "\033[0;31mSomething went wrong during the update!\n\nPlease review the output above carefully, correct the error, and retry the update.\n\nIf you need assistance, get help from the community at https://omarchy.org/discord\033[0m"' ERR
+trap 'echo ""; echo -e "\033[0;31mSomething went wrong during the update!\n\nPlease review the output above carefully, correct the error, and retry the update.\n\nIf you need assistance, get help from the community at https://myarchy.org/discord\033[0m"' ERR
 
-if omarchy-update-confirm; then
-  omarchy-snapshot create || [ $? -eq 127 ]
-  omarchy-update-git
-  omarchy-update-perform
+if myarchy-update-confirm; then
+  myarchy-snapshot create || [ $? -eq 127 ]
+  myarchy-update-git
+  myarchy-update-perform
 fi
